// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcKkP_IYJsfTbKEiNYTiJn_3kGM0FKzPM',
    appId: '1:1034620117926:web:0adead612c61d733fe6567',
    messagingSenderId: '1034620117926',
    projectId: 'surfify',
    authDomain: 'surfify.firebaseapp.com',
    storageBucket: 'surfify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3e2-LgCoY058yyv5B5PSy-rPIrzLLqk',
    appId: '1:1034620117926:android:3a41d5e6ea93f193fe6567',
    messagingSenderId: '1034620117926',
    projectId: 'surfify',
    storageBucket: 'surfify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQIoBX0yG0uOTWEDqX34RkF2WYz8dqzU',
    appId: '1:1034620117926:ios:129d07f53ff57653fe6567',
    messagingSenderId: '1034620117926',
    projectId: 'surfify',
    storageBucket: 'surfify.appspot.com',
    androidClientId:
        '1034620117926-o22ebtimrt2uobkach66kfjft4o68cl3.apps.googleusercontent.com',
    iosClientId:
        '1034620117926-7vmn977ggr82q88jgt4n8a4mnsulred8.apps.googleusercontent.com',
    iosBundleId: 'ai.surfi.snu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQIoBX0yG0uOTWEDqX34RkF2WYz8dqzU',
    appId: '1:1034620117926:ios:129d07f53ff57653fe6567',
    messagingSenderId: '1034620117926',
    projectId: 'surfify',
    storageBucket: 'surfify.appspot.com',
    androidClientId:
        '1034620117926-o22ebtimrt2uobkach66kfjft4o68cl3.apps.googleusercontent.com',
    iosClientId:
        '1034620117926-7vmn977ggr82q88jgt4n8a4mnsulred8.apps.googleusercontent.com',
    iosBundleId: 'ai.surfi.snu',
  );
}
