class keyMap {
  Map<String, String> translations = {
    'cozy': '아늑한',
    'cafe': '카페',
    'restaurant': '레스토랑',
    'car': '차',
    'NSFW': '미성년자 이용 불가',
    'fight': '싸움',
    'food': '음식',
    'oysters': '굴',
    'japanese': '일본어',
    'fancy': '고급스러운',
    'clean': '깨끗한',
    'sanitary': '위생적인',
    'italian': '이탈리아',
    'chinese': '중국어',
    'american': '미국',
    'mexican': '멕시코',
    'thai': '태국',
    'disgusting': '역겨운',
    'ugly': '추한',
    'dirty': '더러운',
    'messy': '무질서한',
    'smelly': '냄새나는',
    'stinky': '냄새나는',
    'filthy': '더러운',
    'gross': '혐오스러운',
    'nudity': '노출',
    'violence': '폭력',
    'boxing': '복싱',
    'love': '사랑',
    'fashion': '패션',
    'photooftheday': '오늘의사진',
    'beautiful': '아름다운',
    'art': '예술',
    'photography': '사진',
    'happy': '행복한',
    'picoftheday': '오늘의사진',
    'cute': '귀여운',
    'nature': '자연',
    'travel': '여행',
    'style': '스타일',
    'summer': '여름',
    'selfie': '셀카',
    'music': '음악',
    'friends': '친구',
    'fitness': '피트니스',
    'girl': '소녀',
    'food': '음식',
    'fun': '즐거운',
    'beauty': '아름다움',
    'smile': '웃음',
    'family': '가족',
    'photo': '사진',
    'life': '삶',
    'ootd': '오늘의 패션',
    'makeup': '메이크업',
    'amazing': '놀라운',
    'dog': '개',
    'model': '모델',
    'sunset': '일몰',
    'beach': '해변',
    'foodporn': '음식사진',
    'motivation': '동기부여',
    'design': '디자인',
    'lifestyle': '라이프스타일',
    'sky': '하늘',
    'cat': '고양이',
    'handmade': '수제품',
    'hair': '머리',
    'nails': '손톱',
    'bestoftheday': '오늘의 최고',
    'vsco': '브이스코',
    'funny': '웃긴',
    'drawing': '그림',
    'artist': '예술가',
    'gym': '체육관',
    'flowers': '꽃',
    'baby': '아기',
    'wedding': '결혼식',
    'pretty': '예쁜',
    'photographer': '사진작가',
    'party': '파티',
    'inspiration': '영감',
    'cool': '멋진',
    'workout': '운동',
    'swag': '스웨그',
    'fit': '체형이 좋은',
    'healthy': '건강한',
    'yummy': '맛있는',
    'foodie': '음식 애호가',
    'moda': '모다',
    'home': '집',
    'christmas': '크리스마스',
    'black': '검은색',
    'memes': '밈',
    'holiday': '휴일',
    'pink': '핑크색',
    'sea': '바다',
    'landscape': '풍경',
    'blue': '파란색',
    'london': '런던',
    'winter': '겨울',
    'night': '밤',
    'puppy': '강아지',
    'tattoo': '타투',
    'happiness': '행복',
    'work': '일',
    'illustration': '일러스트',
    'architecture': '건축',
    'japan': '일본',
    'weekend': '주말',
    'daily': '매일',
    'explore': '탐험',
    'nyc': '뉴욕',
    'coffee': '커피',
    'look': '모습',
    'blessed': '축복받은',
    'spring': '봄',
    'italy': '이탈리아',
    'portrait': '초상화',
    'trip': '여행',
    'shopping': '쇼핑',
    'paris': '파리',
    'dress': '드레스',
    'vacation': '휴가',
    'wanderlust': '방랑욕',
    'health': '건강',
    'goodmorning': '좋은 아침',
    'fashionblogger': '패션 블로거',
    'anime': '애니메이션',
    'red': '빨간색',
    'vintage': '빈티지',
    'travelphotography': '여행 사진',
    'green': '초록색',
    'sweet': '달콤한',
    'meme': '밈',
    'birthday': '생일',
    'luxury': '고급',
    'throwback': '옛날 사진',
    'amor': '사랑',
    'sketch': '스케치',
    'fitfam': '피트니스 가족',
    'delicious': '맛있는',
    'dogs': '개',
    'boy': '소년',
    'new': '새로운',
    'clouds': '구름',
    'relax': '휴식',
    'outfit': '의상',
    'naturephotography': '자연 사진',
    'photoshoot': '사진 촬영',
    'shoes': '신발',
    'sunday': '일요일',
    'bodybuilding': '보디빌딩',
    'artwork': '작품',
    'cats': '고양이',
    'indonesia': '인도네시아',
    'training': '훈련',
    'adventure': '모험',
    'quotes': '인용구',
    'dance': '댄스',
    'dinner': '저녁식사',
    'usa': '미국',
    'nike': '나이키',
    'painting': '그림',
    'canon': '캐논',
    'picture': '사진',
    'morning': '아침',
    'blogger': '블로거',
    'awesome': '멋진',
    'vegan': '비건',
    'mood': '기분',
    'breakfast': '아침식사',
    'nice': '좋은',
    'interior design': '인테리어 디자인',
    'color': '색상',
    'white': '흰색',
    'italian food': '이탈리아 음식',
    'chinese food': '중국 음식',
    'japanese food': '일본 음식',
    'korean people': '한국 사람들',
    'japanese people': '일본 사람들',
    'chinese people': '중국 사람들',
    'This photo contains violence.': '이 사진에는 폭력이 포함되어 있습니다.',
    'Waterbottle': '물병',
  };
}
